<a href="https://colab.research.google.com/github/lin3372/100_datSci/blob/main/05_naive_bayes/156_naive_bayes_1_titanic_survival_prediction_(sklearn_codebasics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

211211

# Naive Bayes Part I
Naive Bayes Tutorial Part 1: Predicting survival from titanic crash [[codebasics github]](https://github.com/codebasics/py/blob/master/ML/14_naive_bayes/14_naive_bayes_1_titanic_survival_prediction.ipynb)

[Youtube Naive Bayes Classifier Algorithm Part 1 (13 min) ](https://www.youtube.com/watch?v=PPeaRc-r1OI)

## Pre-requisite

### directory creation and cleanup, load lib, git clone

In [ ]:
import os
import shutil

In [ ]:
os.getcwd()

'/content/05_naive_bayes'

In [ ]:
# https://github.com/codebasics/py.git
# py/ML/9_decision_tree/9_decision_tree.ipynb
SRC_LOC='/content/py/ML/14_naive_bayes/'

SRC_FILES_DIRS = SRC_LOC + '*'
DST_LOC='/content/'
WORKING_DIR=DST_LOC+'05_naive_bayes/'
!python --version

Python 3.7.12


In [ ]:
shutil.rmtree('/content')
os.mkdir('/content')
os.mkdir(WORKING_DIR)

os.chdir("/content/")
CWD = os.getcwd()
print(f"CWD={CWD}")

if os.path.isdir('py'):
  shutil.rmtree('py')

!git clone https://github.com/codebasics/py

os.system('cp -R ' + SRC_FILES_DIRS + ' ' + WORKING_DIR) 

os.chdir(WORKING_DIR)

CWD=/content
Cloning into 'py'...
remote: Enumerating objects: 2873, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 2873 (delta 33), reused 52 (delta 18), pack-reused 2801
Receiving objects: 100% (2873/2873), 196.64 MiB | 32.63 MiB/s, done.
Resolving deltas: 100% (1112/1112), done.
Checking out files: 100% (1388/1388), done.


## Data Preparation

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  ... Survived
0            1  ...        0
1            2  ...        1
2            3  ...        1
3            4  ...        1
4            5  ...        0

[5 rows x 12 columns]

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [ ]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [ ]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
np.round(inputs.Age[:10], decimals=0)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

## **sklearn - Naive Bayes**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.7761194029850746

In [ ]:
X_test[0:10]

Pclass        Age      Fare  female
537       1  30.000000  106.4250       1
397       2  46.000000   26.0000       0
586       2  47.000000   15.0000       0
425       3  29.699118    7.2500       0
707       1  42.000000   26.2875       0
714       2  52.000000   13.0000       0
220       3  16.000000    8.0500       0
865       2  42.000000   13.0000       1
614       3  35.000000    8.0500       0
562       2  28.000000   13.5000       0

## **Prediction** - Predicting survival from titanic crash 

In [ ]:
y_test[0:10]

537    1
397    0
586    0
425    0
707    1
714    0
220    1
865    1
614    0
562    0
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
model.predict_proba(X_test[:10])

array([[0.00573711, 0.99426289],
       [0.92861186, 0.07138814],
       [0.9315211 , 0.0684789 ],
       [0.96498147, 0.03501853],
       [0.78984694, 0.21015306],
       [0.9303963 , 0.0696037 ],
       [0.95939577, 0.04060423],
       [0.28012363, 0.71987637],
       [0.96619469, 0.03380531],
       [0.92738984, 0.07261016]])

## Calculate the score using **cross validation**

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.768     , 0.744     , 0.84      , 0.74193548, 0.80645161])