<a href="https://colab.research.google.com/github/lin3372/100_datSci/blob/main/05_naive_bayes/156_naive_bayes_2_email_spam_filter_(sklearn_codebasics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

211212

# Naive Bayes Part II
Naive Bayes Tutorial Part 1: Predicting survival from titanic crash [[codebasics github]](https://github.com/codebasics/py/blob/master/ML/14_naive_bayes/14_naive_bayes_2_email_spam_filter.ipynb)

[Youtube Machine Learning Tutorial Python - 15: Naive Bayes Classifier Algorithm Part 2 (11 min) ](https://www.youtube.com/watch?v=nHIUYwN-5rM)

## Pre-requisite

### directory creation and cleanup, load lib, git clone

In [ ]:
import os
import shutil

In [ ]:
os.getcwd()

'/content/05_naive_bayes'

In [ ]:
# https://github.com/codebasics/py.git
# py/ML/9_decision_tree/9_decision_tree.ipynb
SRC_LOC='/content/py/ML/14_naive_bayes/'

SRC_FILES_DIRS = SRC_LOC + '*'
DST_LOC='/content/'
WORKING_DIR=DST_LOC+'05_naive_bayes/'
!python --version

Python 3.7.12


In [ ]:
shutil.rmtree('/content')
os.mkdir('/content')
os.mkdir(WORKING_DIR)

os.chdir("/content/")
CWD = os.getcwd()
print(f"CWD={CWD}")

if os.path.isdir('py'):
  shutil.rmtree('py')

!git clone https://github.com/codebasics/py

os.system('cp -R ' + SRC_FILES_DIRS + ' ' + WORKING_DIR) 

os.chdir(WORKING_DIR)

CWD=/content
Cloning into 'py'...
remote: Enumerating objects: 2873, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 2873 (delta 33), reused 52 (delta 18), pack-reused 2801
Receiving objects: 100% (2873/2873), 196.64 MiB | 28.10 MiB/s, done.
Resolving deltas: 100% (1112/1112), done.
Checking out files: 100% (1388/1388), done.


## Data Preparation

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

In [ ]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

## **sklearn - Naive Bayes**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9849246231155779

## **sklearn pipeline**

In [ ]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
clf.score(X_test,y_test)

0.9849246231155779

In [ ]:
clf.predict(emails)

array([0, 1])